### ISSUE TITLE
Check pairing of tags

### ISSUE THREAD

**Issue by xdmx** [AtomLinter/linter-erb#101]
I'm currently using the last version of Atom and the erb linter. One thing that I miss from other IDEs is the linting of missing pairing tags, for example:

```
<div>
  <%= @foo %>
  <p>
</div>
```

wouldn't complain at all, but it's missing the `</p>`. Is there a way to add this check to the erb linter?

**Comment by ricardograca** [comment]
That is not the responsibility of this package. This only lints ERB code, not HTML. I would love if Atom could use the appropriate linter for each different section of code but I don't think that's possible.

You could try the linter-htmlhint package, but it's kind of a mess.

**Comment by Arcanemagus** [comment]
It's possible, and in fact Linter already works in this way... the problem is that the linters themselves need to be able to parse out the sections of the document that they can understand. Some of the better ones such as ESLint support this, but most do not.

**Comment by ricardograca** [comment]
This linter already extracts all the parts that it can understand out of files. Does that mean that if `linter-htmlhint` is also able to do the same, then both linters can work on a `.erb` file at the same time? Or is there some other change necessary in this linter to get to that point?

**Comment by Arcanemagus** [comment]
Exactly, if `htmlhint` understood how to extract _just_ the HTML parts out, lint them, then return results located in the original file then it could handle ERB files.

Since it has no idea how to do that, it completely fails on the ERB parts of the files.
