### ISSUE TITLE
Migrate CircleCI to a 2.0 configuration

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-erb#112]
CircleCI will be [removing support for 1.0](https://circleci.com/blog/sunsetting-1-0/) configurations as of 2018-08-31. This is one of the repositories within this organization that is currently still configured to use a 1.0 configuration and needs to be migrated to the 2.0 format.

An automated translation can be found [here](https://circleci.com/api/v1.1/project/github/AtomLinter/linter-erb/config-translation), however it is likely that a better method would be to follow the Workflow based example from [AtomLinter/atom-minimap-linter](https://github.com/AtomLinter/atom-minimap-linter/blob/master/.circleci/config.yml).

**Comment by ricardograca** [comment]
I can't access the automated translation link you provided:

```json
{
  "message" : "Permission denied"
}
```
However, it's not super important because I can always just follow the example you linked to.

**Comment by Arcanemagus** [comment]
CircleCI _should_ let anyone that has write access to the repo open that file, but in any case I've uploaded it here:
https://gist.github.com/Arcanemagus/266bbde6a9f5684ca49e1dc0260294bf

I plan on starting on these issues once the next beta build of Atom comes out so the `beta` builds can work under CircleCI, as I'd like to move things to the Workflow based configuration. If you want to take care of this before then though go for it! 😉

There's 6 months to get this all sorted out, which gives us plenty of time, I just wanted to get the issues filed on the repositories that need attention.

**Comment by ricardograca** [comment]
I'm pretty sure it won't take me 6 months to handle this :stuck_out_tongue:

**Comment by ricardograca** [comment]
@Arcanemagus I'm guessing I can't use the `arcanemagus/atom-docker-ci:stable` to test ruby code right? Should I keep using the `circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37` image from that auto-generated config with the following commands to build the stable channel of Atom?

```
- run: curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
- run: chmod u+x build-package.sh
```

What about the Beta channel?

**Comment by ricardograca** [comment]
@Arcanemagus Help?

**Comment by Arcanemagus** [comment]
> I'm guessing I can't use the arcanemagus/atom-docker-ci:stable to test ruby code right?

You would have to install Ruby in the container, the `atom` user in there has passwordless `sudo` so that shouldn't be an issue if you go that route. Alternatively you can keep using their build image that has Ruby pre-installed and let the `atom/ci` build script install Atom for you.

> What about the Beta channel?

Setting this in the environment should make the build script install the beta channel for you: `ATOM_CHANNEL=beta`. For the images I'm building you can just use `arcanemagus/atom-docker-ci:beta` 😉.

> Help?

Sorry 😞! I've been trying, and failing, to keep up with notifications. Feel free to ping me at any time on [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638) as I'll see that better than a @mention here.
