### ISSUE TITLE
Can't support out put expression

### ISSUE THREAD

**Issue by haitaoxu** [AtomLinter/linter-erb#2]
![image](https://cloud.githubusercontent.com/assets/4596479/4432978/5403eeee-46b7-11e4-9b1c-ef5d076bd79f.png)

It can't support '<%=  %>'

If I replace it to '<% %>', and it's ok.

**Comment by eXprojects** [comment]
Sorry for the late reply. I have added a "Ruby on Rails Mode".
Preferences -> Packages -> linter-erb -> Settings
