### ISSUE TITLE
Incorrect Error for '<%= form_for(@var) do |f| %>'

### ISSUE THREAD

**Issue by weilandia** [AtomLinter/linter-erb#25]
ERB Linter is raising an error with the following code when it shouldn't:

<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :quantity %>
  <%= f.text_field :quantity %>
  <%= f.submit %>
<% end %>

![image](https://cloud.githubusercontent.com/assets/13652979/13151636/43e7a88c-d628-11e5-8fb1-2ec44ed7f17a.png)

**Comment by Arcanemagus** [comment]
What do you get if you run `cat foo.erb | erb -x | ruby -c`?

**Comment by Arcanemagus** [comment]
Any updates @weilandia?

**Comment by weilandia** [comment]
Hey, sorry for the delay.  It was a version issue.

**Comment by weilandia** [comment]
Thanks!

**Comment by Arcanemagus** [comment]
Thanks for reporting back!
