### ISSUE TITLE
Incorrect error

### ISSUE THREAD

**Issue by ricardograca** [AtomLinter/linter-erb#36]
This produces an error:

![captura de ecra de 2016-04-05 11 08 06](https://cloud.githubusercontent.com/assets/1457035/14278308/db605d1a-fb1e-11e5-9340-e35c17282b1d.png)

It says "Unexpected ')'", however the code works fine in practice.

Running `cat [my file].erb | erb -x | ruby -c` reveals that:

```
-:15: syntax error, unexpected ')'
      ) do |f| ).to_s); _erbout.concat "\n"
                ^
-:33: syntax error, unexpected end-of-input, expecting ')'
```

### Further investigation

It seems that the issue is caused by a hack implemented by the [Rails ERB handler](https://github.com/rails/rails/blob/9d6e502f81bcf56c7da8a7d1f9e433b4e0a7e3e9/actionpack/lib/action_view/template/handlers/erb.rb#L32) that allows using `<%=` to output what would be invalid ERB syntax, since ERB requires code inside `<%= %>` to be a complete expression that could stand on its own, and obviously `form_for foo do` doesn't stand on its own.

More info in [this blog post](http://timelessrepo.com/block-helpers-in-rails3) and [this stackoverflow question](http://stackoverflow.com/questions/17374274/why-is-this-an-error-with-erb).

In syntastic the problem was worked around by replacing all occurrences of `<%=` with `<%` before passing the text to `erb -x` for compiling, as can be seen [in this commit](https://github.com/scrooloose/syntastic/commit/0f1d451d96970de4b1f07290f6231f9411749919).

### Solution

I'm going to fix this by replacing the current regex based implementation with the same solution that the syntastic project used, since it's much more straightforward, less likely to break something, more accommodating to different ways of writing the block syntax and in practice it shouldn't introduce any errors in the parsed output.

**Comment by Arcanemagus** [comment]
As it looks like this issue is present when run from the command line as well there isn't really anything that can be done about this, other than waiting for somebody to write a real ERB linter as this is just a hack to utilize Ruby's built in one.

Unless there really is something wrong with that code, in which case I wouldn't be the one to ask as I don't work in ERB :stuck_out_tongue:.

**Comment by ricardograca** [comment]
Well, if there was something wrong with the code it wouldn't work when being used on a rails app and it does work :) Using the same version of ruby even.

Something even stranger is happening now. Putting all arguments to `form_for` in the same line so that the whole `<%= form_for ... do |f| %>` is on a single line also produces the exact same error (on a different line obviously) when running the `erb -x` thing from the command line, but produces no error at all on Atom. Any ideas?

**Comment by Arcanemagus** [comment]
It looks like for Rails code in particular it runs some [post-processing](https://github.com/AtomLinter/linter-erb/blob/v1.0.2/lib/index.js#L83-L85) on the output, maybe this is messing things up?

**Comment by ricardograca** [comment]
> 2. Do that modification into out.rb

What specific modification are you talking about?

**Comment by Arcanemagus** [comment]
The one linked in the comment? It looks to do something along the lines of:
Replace all instances of `_erbout.concat((something do somethingelse).to_s)` with just `something do somethingelse`, and as your example output contains that I'm guessing something about that replacement might be breaking things.

**Comment by ricardograca** [comment]
That's it. I think I know what the problem is.

Here's the minimum template that produces the syntax warning in `erb -x | ruby -c` but not on Atom:

```erb
<%= form_for resource do |f| %>
<% end %>
```

This is the output from `erb -x`:

```ruby
#coding:ASCII-8BIT
_erbout = ''; _erbout.concat(( form_for resource do |f| ).to_s); _erbout.concat "\n"
;  end ; _erbout.concat "\n"
; _erbout.force_encoding(__ENCODING__)
```

The output above will cause the "Unexpected ')'" syntax error when passed through `ruby -c`. Now this is the output after passing the above output through the post-processing function mentioned previously:

```ruby
#coding:ASCII-8BIT
_erbout = '';  form_for resource do |f| ; _erbout.concat "\n"
;  end ; _erbout.concat "\n"
; _erbout.force_encoding(__ENCODING__)
```

With this code there are no more syntax errors, probably because the `form_for` block that is missing the `end` keyword (since it is in another line) can now be correctly parsed.

Now, when using the multi-line version of the `form_for` method the post-processing is never applied due to the newlines in between the other valid regex characters, so the fix is quite simple: replace the `.`'s (which match any character except line breaks) in the regex with `[\s\S]` which will match any characters including line breaks:

```js
/_erbout.concat\(\(([\s\S]+?do[\s\S]+?)\).to_s\)/g
```

I can provide a PR for this. I'll make the change to my local copy of the package and see if it causes any other problems.

**Comment by ricardograca** [comment]
The solution mentioned in the previous message needs a few tweaks since the regex will incorrectly catch this:

```erb
<%= something %>
<p>Blah blah do</p>
<%= something_else %>
```

**Comment by Arcanemagus** [comment]
I'll be happy to merge any PR as it seems you have a grasp on the issue and the solution :wink:

You wouldn't happen to be interested in maintaining this linter would you? I don't use ERB myself, so currently this project has no maintainer that actually uses it.

**Comment by ricardograca** [comment]
I don't use it all the time as well, but sure, if there's no one else more suited I wouldn't mind maintaining it. Also, this is the only issue so it should be easy.
