### ISSUE TITLE
linter-erb does not respect custom ruby

### ISSUE THREAD

**Issue by bovender** [AtomLinter/linter-erb#90]
Linter-erb runs the Ruby that is installed system-wide with the package manager and does not respect a custom Ruby version that is installed using [rbenv](https://github.com/rbenv/rbenv).

I am running Ubuntu 16.10 which comes with Ruby 2.3.1. Using `rbenv install 2.3.3 && rbenv global 2.3.3` I have switched my standard Ruby to 2.3.3, but that is not picked up by linter-erb. As a result, I get this warning in Atom:

> Error: warning: parser/current is loading parser/ruby23, which recognizes
warning: 2.3.3-compliant syntax, but you are running 2.3.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
    at ChildProcess.<anonymous> (/home/daniel/.atom/packages/linter-erb/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)

I've tried to use `` `rbenv which ruby` `` (with backticks) in the "Ruby Executable Path" setting, but that does not work. Neither does placing the literal path in the settings field work: `/home/daniel/.rbenv/versions/2.3.3/bin/ruby`. Still the same warning.

Interestingly, the warning is not shown if I launch Atom from the terminal. Could this be related to #37?

**Comment by bovender** [comment]
Please disregard this. The problem occurs in linter-haml, not linter-erb, and it can be remedied by putting `/home/user/.rbenv/shims/haml-lint` in the `Executable Path` setting (if using rbenv to manage Rubies).

My apologies for posting to the wrong tracker.

**Comment by ricardograca** [comment]
No problem!
