### ISSUE TITLE
Special characters must be escaped : [ < ].

### ISSUE THREAD

**Issue by mvasin** [AtomLinter/linter-erb#94]
Why does the linter flag any ruby code embedded into erb inappropriate? Here's the document.erb:

```
<!DOCTYPE html>
<% start = Time.now %>
```

Here's the error:
```
Special characters must be escaped : [ < ]
```

Here comes the screenshot:

<img width="1037" alt="screen shot 2017-03-30 at 12 00 42" src="https://cloud.githubusercontent.com/assets/12434833/24496302/8af70260-1540-11e7-8136-178da36ebfd1.png">

**Comment by mvasin** [comment]
Oh, I think I see it: "provider" is htmlhint. But how do I change it?

**Comment by ricardograca** [comment]
Personally I just uninstalled htmlhint since it tries to lint more file types than it should and that causes more problems than it solves. However, if you really care about it you should create a new bug report over on [its repo](https://github.com/AtomLinter/linter-htmlhint).

**Comment by mvasin** [comment]
Thanks!

**Comment by Arcanemagus** [comment]
I've tried several times to limit that provider to file types it actually understands, but the author insists on having it list virtually every type 😞.

**Comment by mvasin** [comment]
On the other hand, after switching off htmlhint, html part of code doesn't seem to be linted.
