### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by akarpas** [AtomLinter/linter-erb#98]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [linter-erb](https://github.com/AtomLinter/linter-erb) package 1.1.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /Users/karpas/.atom/packages/linter-erb/node_modules/graceful-fs/polyfills.js:21

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at process.chdir (/packages/linter-erb/node_modules/graceful-fs/polyfills.js:21:9)
    at process.chdir (/packages/linter-xo/node_modules/graceful-fs/polyfills.js:21:9)
    at lint (/packages/jshint/index.js:229:10)
    at complete (/packages/jshint/node_modules/lodash/index.js:7697:25)
    at delayed (/packages/jshint/node_modules/lodash/index.js:7707:11)
```

### Commands

```
```

### Non-Core Packages

```
atom-runner 2.7.1 
busy-signal 1.4.1 
color-picker 2.2.5 
emmet 2.4.3 
es6-javascript 1.0.0 
intentions 1.1.2 
jshint 1.8.6 
linter 2.1.4 
linter-erb 1.1.0 
linter-ruby 1.2.5 
linter-ui-default 1.2.3 
linter-xo 0.23.0 
minimap 4.28.2 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
sass-autocompile 0.13.3 
script 3.14.1 
```

**Comment by Arcanemagus** [comment]
> `at lint (/packages/jshint/index.js:229:10)`

This is actually coming from the long deprecated [jshint](https://atom.io/packages/jshint) package. If you _really_ need JSHint support you should uninstall that package and install `linter-jshint`, however I would _highly_ recommend switching to ESLint as it is a _much_ better linter.
